services:
  # Banco de dados MongoDB
  mongodb:
    image: mongodb/mongodb-community-server
    container_name: react_test_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      # MONGO_INITDB_ROOT_USERNAME: admin
      # MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: users_database
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
