- name: Run Frontend Tests with Coverage
  run: |
    cd frontend
    npm run test:coverage

- name: Debug Coverage Detalhado
  run: |
    echo "=== Coverage Directory ==="
    ls -la frontend/coverage/
    echo ""
    echo "=== LCOV Info (primeiras 30 linhas) ==="
    head -30 frontend/coverage/lcov.info
    echo ""
    echo "=== Contagem de arquivos no LCOV ==="
    grep -c "^SF:" frontend/coverage/lcov.info || echo "0 arquivos"
    echo ""
    echo "=== Paths no LCOV ==="
    grep "^SF:" frontend/coverage/lcov.info
    echo ""
    echo "=== Coverage Summary JSON ==="
    if [ -f frontend/coverage/coverage-final.json ]; then
      # Verificar se há coverage > 0
      node -e "
        const coverage = require('./frontend/coverage/coverage-final.json');
        const files = Object.keys(coverage);
        console.log('Arquivos com coverage:', files.length);
        files.forEach(file => {
          const statements = coverage[file].s;
          const executed = Object.values(statements).filter(s => s > 0).length;
          const total = Object.values(statements).length;
          console.log(\`\${file}: \${executed}/\${total} statements executed\`);
        });
      "
    fi

- name: SonarQube Scan
  uses: SonarSource/sonarqube-scan-action@v4
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
