on:
  push:
    branches:
      - main
      - develop
      - "releases/**"
  pull_request:
    types: [opened, synchronize, reopened]

name: Build Workflow
jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.14.0"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm ci

      - name: Run Frontend Tests with Coverage
        run: |
          cd frontend
          npm run test:coverage

      - name: Verify Coverage Files
        run: |
          ls -la frontend/coverage/
          cat frontend/coverage/lcov.info | head -20

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
